database:
  path: "database.db"  # Path to the SQLite database file

turnstile:
  secret_key: "0x4AAAAAAA2_Yq2QkGh8RQfVoBP_KJNPABI"

server:
  url: "shrinx.isawebapp.com"
  port: 15000

domains:
  - "shrinx.isawebapp.com"

admin:
  username: 'admin'       # Set your desired admin username
  password: 'admin'    # Set your desired admin password