database:
  path: "database.db"  # Path to the SQLite database file

turnstile:
  secret_key: "0x4AAAAAAA2_Yq2QkGh8RQfVoBP_KJNPABI"

server:
  url: "localhost"
  port: 5000

domains:
  - "localhost"

admin:
  username: 'admin'       # Set your desired admin username
  password: 'admin'    # Set your desired admin password