database:
  path: "database.db"  # Path to the SQLite database file

turnstile:
  secret_key: "secret_key"

url: "localhost:5000"

server:
  port: 5000

domains:
  - "domain.com"

admin:
  username: 'admin'       # Set your desired admin username
  password: 'password'    # Set your desired admin password